services:

  db-deciva:
    image: postgres:16
    container_name: db_deciva
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_deciva_data:/var/lib/postgresql/data
    networks:
      - deciva_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ui-deciva:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui_deciva
    ports:
      - "${PORT:-9512}:8080"
    environment:
      TZ: "America/El_Salvador"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      DB_CONNECTION: ${DB_CONNECTION}
    depends_on:
      db-deciva:
        condition: service_healthy
    networks:
      - deciva_network
    restart: always

volumes:
  db_deciva_data:

networks:
  deciva_network:
    name: deciva_network
